[lint]
select = ["E", "W", "F", "I", "N", "UP", "B", "C4", "SIM", "RUF"]
ignore = ["E501"]

[format]
line-length = 79
target-version = "py312"

[lint.isort]
known-first-party = ["github_actions_ai_analyzer"]